### ISSUE TITLE
Compatibility with newer versions of scikit-learn

### ISSUE THREAD

**Issue by hclimente** [Chester75321/GenEpi#1]
Hello,

I am running into some issues when running GenEpi, consequence of some changes to the interface of some scikit-learn functions. For the moment, I have run into the following issues:

from sklearn.cross_validation import KFold -> from sklearn.model_selection import KFold
from sklearn import grid_search -> from sklearn.model_selection import GridSearchCV
KFold function has changed.

Cheers,
Héctor.

**Comment by Chester75321** [comment]
Hi Héctor,

Thanks for notice. I will resolve these issues in next update.

Cheers,
Chester
