### ISSUE TITLE
Inquiry about the datasets.

### ISSUE THREAD

**Issue by MatZlo** [Chester75321/GenEpi#3]
Hello, I've been studying your paper and code and it is very interesting. I think that I understand the general concepts but I'm very new to working with genetics data so I have a few questions.

**Could you please point me to the source of the example data? (sample.gen and sample.csv.)**

I understand that sample.gen is the genotype data, and sample.gen is the phenotype data but I've yet to find the source of either of them.

From what I've managed to figure out so far:
Genotype data is:  [chromosome_num, SNP_reference_sequence_id, position_on_chromosome, base_pairs?, ?].
Phenotype data is : [?, Odds ratio, class]

I've managed to get similar data to yours by using the GAMATES software that you mentioned in your paper but a lot of data that is present in the example inputs is missing.

Thank you for your time.

**EDIT: I found the documentation** 
**https://genepi.readthedocs.io/en/latest/format.html#input-genotype-data**

**Comment by Chester75321** [comment]
Hi MatZlo,

Thanks for your feedback and for using GenEpi.

Here is the example of input data
https://github.com/Chester75321/GenEpi/tree/master/genepi/example
For the detail description of the input data, please refer to the document:
https://genepi.readthedocs.io/en/latest/format.html

According to your example, the contents should be:
Genotype data is: [chromosome_num, SNP_reference_sequence_id,
position_on_chromosome, alternative_allele, reference_allele,
sample1_homozygote_alternative_allele, sample1_heterozygote,
sample1_homozygote_reference_allele, sample2_homozygote_alternative_allele,
sample2_heterozygote, sample2_homozygote_reference_allele,...].
(please see as: https://www.cog-genomics.org/plink/1.9/formats#gen)
Phenotype data is : [covariate_1, covariate_2, ..., class_of_phenotype]

I used GAMETES to generate simulation data indeed, but the data format of
GAMETES cannot be used for GenEpi directly. If you were looking for example
data. please execute the shell command: GenEpi -g example -p example -o ./,
which will generate example data and results for you in the current
directory.

Best,
Chester

MatZlo <notifications@github.com> 於 2020年5月5日 週二 上午4:50寫道：

**Comment by MatZlo** [comment]
Sorry for the late reply, but thank you a lot for the explanation! You helped me a lot.
________________________________
